import CPlaydate

/// One of the games bundled with this application.
///
/// The games themselves are listed in `carts.txt`, which is the one place they
/// are named: `tools/carts.sh` generates the array from it, along with the
/// table of licences in THIRD-PARTY.md, and `tools/fetch-assets.sh` downloads
/// what it names.
struct CartEntry {
    let title: StaticString
    let path: StaticString
    /// Path to the cover image, without the extension, as loadBitmap wants it.
    /// The images are generated by this runtime; see tools/covers.
    let cover: StaticString
}


/// The shelf: a crank-scrolled list of the bundled games.
///
/// The crank is the reason this is a list rather than a grid. WASM-4 has no
/// notion of it, so the shelf can use it without taking anything away from a
/// cart.
struct Shelf {
    /// Degrees of crank travel per row. A full turn moves twelve rows, which
    /// is a comfortable rate for a list this length.
    static let degreesPerRow: Float = 30

    private(set) var selection = 0
    private var accumulated: Float = 0

    /// Advances the selection from crank movement and returns true if the
    /// highlighted row changed.
    mutating func advance(crankChange: Float) -> Bool {
        accumulated += crankChange
        var moved = false

        while accumulated >= Self.degreesPerRow {
            accumulated -= Self.degreesPerRow
            if selection < carts.count - 1 {
                selection += 1
                moved = true
            }
        }
        while accumulated <= -Self.degreesPerRow {
            accumulated += Self.degreesPerRow
            if selection > 0 {
                selection -= 1
                moved = true
            }
        }
        return moved
    }

    mutating func move(by delta: Int) -> Bool {
        let next = max(0, min(carts.count - 1, selection + delta))
        guard next != selection else { return false }
        selection = next
        accumulated = 0
        return true
    }
}
